//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBCCR.wsIndicadoresEconomicos {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.sdde.bccr.fi.cr", ConfigurationName="wsIndicadoresEconomicos.wsIndicadoresEconomicosSoap")]
    internal interface wsIndicadoresEconomicosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerIndicadoresEconomicos(string tcIndicador, string tcFechaInicio, string tcFechaFinal, string tcNombre, string tnSubNiveles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicosXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ObtenerIndicadoresEconomicosXML(string tcIndicador, string tcFechaInicio, string tcFechaFinal, string tcNombre, string tnSubNiveles);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface wsIndicadoresEconomicosSoapChannel : ConexionBCCR.wsIndicadoresEconomicos.wsIndicadoresEconomicosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class wsIndicadoresEconomicosSoapClient : System.ServiceModel.ClientBase<ConexionBCCR.wsIndicadoresEconomicos.wsIndicadoresEconomicosSoap>, ConexionBCCR.wsIndicadoresEconomicos.wsIndicadoresEconomicosSoap {
        
        public wsIndicadoresEconomicosSoapClient() {
        }
        
        public wsIndicadoresEconomicosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsIndicadoresEconomicosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsIndicadoresEconomicosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsIndicadoresEconomicosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ObtenerIndicadoresEconomicos(string tcIndicador, string tcFechaInicio, string tcFechaFinal, string tcNombre, string tnSubNiveles) {
            return base.Channel.ObtenerIndicadoresEconomicos(tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles);
        }
        
        public string ObtenerIndicadoresEconomicosXML(string tcIndicador, string tcFechaInicio, string tcFechaFinal, string tcNombre, string tnSubNiveles) {
            return base.Channel.ObtenerIndicadoresEconomicosXML(tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles);
        }
    }
}
