//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.ERPAsientos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ERPAsientos.IERPAsientos")]
    public interface IERPAsientos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IERPAsientos/ingresarNuevoAsiento", ReplyAction="http://tempuri.org/IERPAsientos/ingresarNuevoAsientoResponse")]
        int ingresarNuevoAsiento(System.DateTime pFechaDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IERPAsientos/ingresarCuentasAsiento", ReplyAction="http://tempuri.org/IERPAsientos/ingresarCuentasAsientoResponse")]
        int ingresarCuentasAsiento(int pIdAsiento, int pIdCuenta, decimal pMontoLocal, decimal pMontoSistema, bool pDebeHaber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IERPAsientosChannel : UI.ERPAsientos.IERPAsientos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ERPAsientosClient : System.ServiceModel.ClientBase<UI.ERPAsientos.IERPAsientos>, UI.ERPAsientos.IERPAsientos {
        
        public ERPAsientosClient() {
        }
        
        public ERPAsientosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ERPAsientosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERPAsientosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERPAsientosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ingresarNuevoAsiento(System.DateTime pFechaDocumento) {
            return base.Channel.ingresarNuevoAsiento(pFechaDocumento);
        }
        
        public int ingresarCuentasAsiento(int pIdAsiento, int pIdCuenta, decimal pMontoLocal, decimal pMontoSistema, bool pDebeHaber) {
            return base.Channel.ingresarCuentasAsiento(pIdAsiento, pIdCuenta, pMontoLocal, pMontoSistema, pDebeHaber);
        }
    }
}
